appletouchicon: /media/apple-touch-icon.png #ä½ å›¾ç‰‡çš„è·¯å¾„

# Sidebar profile
profile:
  # ä¹Ÿå¯ä»¥ç›´æ¥è®¾ç½®å¤´åƒ URL
  avatar: https://picx.zhimg.com/v2-a9c966774c2d1f924a3ffe3fb85db199_1440w.jpg?source=172ae18b

  # ä¸ªæ€§ç­¾å
  bio: Awesome.

menu:
  ğŸ“– Blog: https://man-her.tech
  ğŸ¤–ï¸ ChatGPT: https://chat.man-her.tech

appearance:
  # Accent color, default '#2a2b33'
  accent_color:
  # Font color, default '#363636'
  foreground_color:
  # Border color, default '#e0e0e0'
  border_color:
  # body background, default '#f5f7fa'
  background:
  # Sidebar background (when opened), default to accent_color
  sidebar_background:
  # Card background, default '#fff'
  card_background:

  # All background settings above support image, e.g.,
  # '//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png #f5f7fa' or
  # 'url(//www.toptal.com/designers/subtlepatterns/patterns/confectionary.png) #f5f7fa'

  # å†…å®¹åŒºåŸŸæœ€å¤§å®½åº¦
  content_width: 800

  # å­—ä½“è®¾ç½®
  font:
    # å­—ä½“ CSS æ–‡ä»¶çš„ URL
    url: //fonts.googleapis.com/css?family=Baloo+Bhaijaan|Inconsolata|Josefin+Sans|Montserrat|Fira+Code

    # åŸºç¡€å­—ä½“ï¼Œä½œç”¨äº body å…ƒç´ 
    base: "'Josefin Sans', 'PingFang SC', Microsoft YaHei"
    # ä½œç”¨äº sidebar ä¸Šæ–¹çš„ LOGO
    logo:
    # ä½œç”¨äº sidebar èœå•æ 
    menu: "Baloo Bhaijaan"
    # ä½œç”¨äºæ–‡ç« ç™¾åˆ†æ¯”ã€å½’æ¡£é¡µæœˆä»½ã€åˆ†ç±»æ–‡å­—æ•°ã€åˆ†é¡µã€ç›®å½•ç´¢å¼•ç­‰åœ°æ–¹
    label: Montserrat
    # ä½œç”¨äºæ ‡é¢˜
    heading:
    # ä½œç”¨äºä»£ç åŠä»£ç å—
    code: Fira Code, monospace
    # Base font for printing which applied to body
    print:

  # ä»£ç è¯­æ³•é«˜äº®
  # æ¥å—è®¾ç½®å€¼ä¸º 16 ä¸ª hex è‰²å€¼çš„æ•°ç»„ï¼Œå…·ä½“è¯·å‚è€ƒ base16 (https://github.com/chriskempson/base16)
  # é»˜è®¤é…è‰²æ–¹æ¡ˆä¸º Atelier Dune Light
  # google light
  highlight:
    [
      "#ffffff",
      "#e0e0e0",
      "#c5c8c6",
      "#b4b7b4",
      "#969896",
      "#373b41",
      "#282a2e",
      "#1d1f21",
      "#cc342b",
      "#f96a38",
      "#fba922",
      "#198844",
      "#3971ed",
      "#3971ed",
      "#a36ac7",
      "#3971ed",
    ]

  # å¯ç”¨ darkmode
  darkmode:
    accent_color: "#539bf5"
    foreground_color: "#adbac7"
    border_color: "#373e47"
    background: "#22272e"
    sidebar_background: "#22272e"
    card_background: "#2d333b"
    # google dark
    highlight:
      [
        "#1d1f21",
        "#282a2e",
        "#373b41",
        "#969896",
        "#b4b7b4",
        "#c5c8c6",
        "#e0e0e0",
        "#ffffff",
        "#cc342b",
        "#f96a38",
        "#fba922",
        "#198844",
        "#3971ed",
        "#3971ed",
        "#a36ac7",
        "#3971ed",
      ]
